name: CI-CD-Pipeline-to-AWS-Amplify-Manual-Deployment
env:
  AMPLIFY_PACKAGE_S3_BUCKET_NAME: "amplify-manual-deploy-trail"
  AWS_REGION: "us-west-2"
  APP_ID: "ABC123xyz" 
  PACKAGE_NAME: "build"
 
on:
  workflow_dispatch:
  
jobs:
  ci-pipeline:
    runs-on: [ubuntu-latest]
    steps:      
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build --if-present
    
      - name: Create Zip Deployment Package
        run: cd build && zip -r $PACKAGE_NAME * -x *.git*


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Copy Deployment Package to AWS S3
        run: |
          cd build && \
          aws s3 cp $PACKAGE_NAME s3://$AMPLIFY_PACKAGE_S3_BUCKET_NAME

  cd-pipeline:
    runs-on: ubuntu-latest
    needs: [ci-pipeline]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION
     
      - name: Deploy the new application version
        run: |
          aws amplify start-deployment \
            --app-id $APP_ID \
            --branch-name manual \
            --source-url s3://$AMPLIFY_PACKAGE_S3_BUCKET_NAME/$PACKAGE_NAME.zip 
